CREATE TABLE "project_directory" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"name_normalized" text NOT NULL,
	"developer" text DEFAULT '' NOT NULL,
	"area" text DEFAULT '' NOT NULL,
	"sub_location" text DEFAULT '' NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'off_plan' NOT NULL,
	"rera_number" text DEFAULT '' NOT NULL,
	"escrow_bank" text DEFAULT '' NOT NULL,
	"handover_date" text,
	"launch_date" text,
	"total_units" integer,
	"amenities" text DEFAULT '[]' NOT NULL,
	"currency" text DEFAULT 'AED' NOT NULL,
	"golden_visa_eligible" boolean DEFAULT false NOT NULL,
	"unit_types_json" text DEFAULT '[]' NOT NULL,
	"comparable_projects_json" text DEFAULT '[]' NOT NULL,
	"times_used" integer DEFAULT 0 NOT NULL,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now() NOT NULL,
	CONSTRAINT "project_directory_name_normalized_unique" UNIQUE("name_normalized")
);
